import Header from "@/components/backtest/Header";
import DiversificationMetrics from "@/components/backtest/correlation/DiversificationMetrics";
import StrategyComparisonTable from "@/components/backtest/correlation/StrategyComparisonTable";
import CorrelationMatrices from "@/components/backtest/correlation/CorrelationMatrices";
import EquityComparisonCharts from "@/components/backtest/correlation/EquityComparisonCharts";
const CorrelationReport = () => {
  return <div className="min-h-screen bg-background text-foreground">
      <Header />

      {/* Hero Section */}
      <section className="py-8 border-b border-white/10 text-center">
        <div className="container mx-auto px-6">
          <h1 className="text-2xl md:text-3xl font-bold mb-2 text-primary">DF717</h1>
          <h2 className="text-xl md:text-2xl font-semibold mb-2">
            Strategy Correlation Report
          </h2>
          <p className="text-muted-foreground text-sm">
            Generated: {new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'numeric',
            day: 'numeric'
          })}, {new Date().toLocaleTimeString('en-US', {
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false
          })}
          </p>
        </div>
      </section>

      {/* Main Content */}
      <div className="container mx-auto px-6 py-8 max-w-6xl">
        <div className="space-y-12">

          {/* 1. Diversification Metrics (4 cards) */}
          <DiversificationMetrics />

          {/* 2. Strategy Comparison Table */}
          <StrategyComparisonTable />

          {/* 3. Correlation Matrices (Pearson, Spearman, Win/Loss, DD Overlap) */}
          <CorrelationMatrices />

          {/* 4. Equity Comparison Charts */}
          <EquityComparisonCharts />

        </div>
      </div>

      {/* Footer */}
      <footer className="py-8 border-t border-white/10 mt-8">
        <div className="container mx-auto px-6 text-center">
          <p className="text-sm text-muted-foreground">
            Generated by <span className="text-primary font-medium">BLODSALGO Analytics</span> • For educational purposes only
          </p>
        </div>
      </footer>
    </div>;
};
export default CorrelationReport;