import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";
import DiversificationMetrics from "@/components/backtest/correlation/DiversificationMetrics";
import StrategyComparisonTable from "@/components/backtest/correlation/StrategyComparisonTable";
import CorrelationMatrices from "@/components/backtest/correlation/CorrelationMatrices";
import EquityComparisonCharts from "@/components/backtest/correlation/EquityComparisonCharts";

const CorrelationReport = () => {
  return <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <div className="border-b border-border py-8">
        <div className="container mx-auto px-6">
          <div className="flex items-center justify-between mb-4">
            <Link 
              to="/" 
              className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Overview
            </Link>
          </div>
          <div className="text-center">
            <h1 className="text-2xl font-bold">
              <span className="text-foreground">DF</span>
              <span className="text-primary">717</span>
              <span className="text-muted-foreground ml-2">Analytics</span>
            </h1>
            <p className="text-muted-foreground mt-1">Strategy Correlation Report</p>
            <p className="text-xs text-muted-foreground font-mono mt-2">
              Generated: {new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'numeric',
                day: 'numeric'
              })}, {new Date().toLocaleTimeString('en-US', {
                hour: '2-digit',
                minute: '2-digit',
                second: '2-digit',
                hour12: false
              })}
            </p>
          </div>
        </div>
      </div>

      {/* Main Content */}
      <main className="container mx-auto px-6 py-8 max-w-7xl">
        <div className="space-y-12">

          {/* 1. Diversification Metrics (4 cards) */}
          <DiversificationMetrics />

          {/* 2. Strategy Comparison Table */}
          <StrategyComparisonTable />

          {/* 3. Correlation Matrices (Pearson, Spearman, Win/Loss, DD Overlap) */}
          <CorrelationMatrices />

          {/* 4. Equity Comparison Charts */}
          <EquityComparisonCharts />

        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-8 mt-8">
        <div className="container mx-auto px-6 text-center">
          <p className="text-sm text-muted-foreground">
            Generated by <span className="text-primary font-medium">BLODSALGO Analytics</span> • For educational purposes only
          </p>
        </div>
      </footer>
    </div>;
};
export default CorrelationReport;